#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Verificando todo o código estabelecido antes do commit"

yarn check-all || 
( 
  echo "Calma lá, foi encontrado um erro, revisa o código do commit e volta depois."
)

echo "Ok ok, aparentemente ta tudo certo, testando a build da aplicação antes do commit"

yarn build || 
( 
  echo "Eita, olha o perigo, deu um erro ao realizar a build, corrigi o erro e commita novamente"
)

echo "Você venceu... esta vez. Estou comitando agora."
